### ISSUE TITLE
Twitterfeed implementation

### ISSUE THREAD

**Issue by kellerrennkadse** [savetheinternetinfo/website#25]
There needs to be a backend implementation of the communication with twitter to fetch the latest tweets

**Comment by Pacerino** [comment]
Im Backend wurde jetzt das holen der Tweets mittels API implementiert.
Es werden jeweils 20 Tweets mit dem Hashtag _FCKArt13_ in den Cache geschrieben.

Der Cache ist 10 Minuten lang gültig, danach werden neue Tweets geholt.

### TODO:

- [x] Holen der Tweets mittels Twitter API

- [x] Tweets in den Cache speichern

- [ ] Einfügen der Tweets in das Frontend

- [ ] Promise Catch so anpassen dass wenn es nicht möglich ist Tweets zu holen, dennoch die Seite angezeigt wird

Vielleicht kann sich jemand mal 2ba47debd938fc089ec21f4f2d088501abcac6d6 anschauen und sagen ob dies so in Ordnung ist oder ehr nicht!

**Comment by Pacerino** [comment]
- Cache ist 10 Minuten lang gültig

- Hashtags: FCKArt13, SaveTheInternet, Uploadfilter

- Jede Minute wird auf dem Frontend ein neuer Tweet eingeblendet bis keine mehr vorhanden sind

- Zeitangabe beim Tweet werden in der jeweiligen ausgewählten Sprache angezeigt. (Außer Chinesisch, da ist es Englisch)
